baseurl = "https://www.rheakara.com"
title = "Rhea Kara"
author = "You"
copyright = "Your Copyright"
canonifyurls = true
paginate = 5
pluralizelisttitles = false

googleAnalytics = "UA-84231237-1"

theme = "mila"

[params]
    author = "Rhea Kara Le"
    email = "hello@rheakara.com"
    hero = "/img/kitty1.jpg"
    name = "Rhea Kara"
    description = "Welcome to my page"

[params.nf404]
    name = "404"
    description = "The droids are not here"
    hero = "/img/kitty1.jpg"

[params.menu]
    [params.menu.blog]
        name = "blog"
        description = "A collection of thoughts and opinions"
        hero = "/img/blog.jpg"
        url = "/blog/"
        weight = 1

    [params.menu.about]
        name = "about"
        url = "/about/"
        weight = 3
